### ISSUE TITLE
forms errors

### ISSUE THREAD

**Issue by cesagonchu** [mambax7/liaise#3]
Tested with LIAISE 2.10 Beta 1 (02/14/2021) https://github.com/mambax7/liaise and Xoops 2.5.11 latest version.

A) When I try to send a feedback on user side (Home » All forms » Send feedback) I get this error:

`Error: Call to a member function getVar() on bool in file /modules/liaise/include/form_execute.php line 47`

B) When I want to create a form on admin side I get this popup message:

![image](https://user-images.githubusercontent.com/4613970/128602026-5a2f24cf-7b37-44a1-b910-021fccce6d7c.png)

___
My config:

Apache/2.4.18 (Ubuntu)
PHP version 7.4.9
MySQLi extension mysqlnd 7.4.9

**Comment by mambax7** [comment]
See if this update https://github.com/mambax7/liaise/commit/967dd1cae306503f2ac79445979ebe6ac27792c4 has fixed that

**Comment by cesagonchu** [comment]
Same error on admin side and on user side the captcha doesn't show and I get this error:
`Error: Class 'XoopsModules/Liaise/Captcha/CaptchaX' not found in file /modules/liaise/index.php line 121`

**Comment by mambax7** [comment]
Try to rename the file class/Captcha/Captchax.php to CaptchaX.php

**Comment by mambax7** [comment]
Seems to be working fine now:
![image](https://user-images.githubusercontent.com/613686/128622104-3a59f302-f723-484b-ae00-60bb177fa449.png)
